language: c

before_install:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x
  - sudo apt-get update
  - sudo apt-get install cmake
  - cmake --version

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ls -la